### ISSUE TITLE
ustvnow and download of recordings

### ISSUE THREAD

**Issue by sebDK** [stephensolis/ustvnow-client#2]
Hi @stephensolis ,

First thank you for your code, It is great!
I was wondering if you will add a new feature to download the recordings.

Again thank you for your greate code.

S.

**Comment by stephensolis** [comment]
I'd love to be able to, but I don't have a paid account so I can't test the DVR feature :slightly_frowning_face:

**Comment by sebDK** [comment]
You do not need a premium account to record shows. It is just limited to 5 pieces. 
I tried to look at that. But I do not succeed anymore in downloading the recordings by pieces. 
It looks like UsTvNow blocks curl or wget to download pieces. I tried to use user-agent spoofing but without success.....

**Comment by aykuter** [comment]
@stephensolis first of all thank you soo much for this script. It's working very well. Beside the dvr download feature is there any way to record live stream ? I don't wanna use any third party tool for that. If it's that possible with python can you give me an idea ? I'm beginner programmer but i will try to code it.

**Comment by stephensolis** [comment]
Sorry, I don't have time to maintain this project anymore.

Please feel free to fork!
